alias ll='ls -lah --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias bc='bc -l'
alias update='sudo apt-get update && yes | sudo apt-get upgrade'
alias cls='printf "\033c"'
alias cp='cp -v'
alias mv='mv -v'
alias ln='ln -v'
alias du='du -h'
alias gl='git log --all --graph --decorate --oneline'
